// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrkptlznirsvxzlqmdsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlya3B0bHpuaXJzdnh6bHFtZHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTkxMDYsImV4cCI6MjA2NzM5NTEwNn0.xogqVvJwTtSAX12GK0OTwXVt9s1v06xJrgIgtIf7LJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});